generate.only_alive_patients = true
generate.diabetes.prevalence = 0.3
generate.hypertension.prevalence = 0.4
generate.cardiovascular_disease.prevalence = 0.2
generate.obesity.prevalence = 0.5
exporter.fhir.extensions.social_determinants = true
exporter.fhir.extensions.us_core = true
exporter.fhir.observation.value_sets = expanded
